---
# handlers file for role-template

- name: "Restart Apache"
  sudo: yes
  action: service name={{ piwik-ssl.apache.service }} state=restarted

- name: "Reload Apache"
  sudo: yes
  action: service name={{ piwik-ssl.apache.service }} state=reloaded

- name: "Start Apache, if not running"
  sudo: yes
  action: service name={{ piwik-ssl.apache.service }} state=started

- name: "Stop Apache, if running"
  sudo: yes
  action: service name={{ piwik-ssl.apache.service }} state=stopped
  